export const diff = {
  before: {
    name: "src/greet.ts",
    contents: `export function greet(name: string) {
  return \`Hello, \${name}!\`
}
`,
  },
  after: {
    name: "src/greet.ts",
    contents: `export function greet(name: string, excited = false) {
  const message = \`Hello, \${name}!\`
  return excited ? \`\${message}!!\` : message
}
`,
  },
}

export const code = {
  name: "src/calc.ts",
  contents: `export function sum(values: number[]) {
  return values.reduce((total, value) => total + value, 0)
}

export function average(values: number[]) {
  if (values.length === 0) return 0
  return sum(values) / values.length
}
`,
}

export const markdown = [
  "# Markdown",
  "",
  "Use **Markdown** for rich text.",
  "",
  "## Highlights",
  "- Headings, lists, and code blocks",
  "- Inline `code` and links",
  "",
  "```ts",
  "export const value = 42",
  "```",
  "",
  "## Tables",
  "",
  "| Region | Q1 | Q2 | Q3 |",
  "| --- | --: | --: | --: |",
  "| Americas | 124 | 142 | 158 |",
  "| EMEA | 88 | 102 | 117 |",
  "| APAC | 64 | 79 | 95 |",
  "",
  "## Math",
  "",
  "Inline: $E = mc^2$ — block:",
  "",
  "$$\\int_{a}^{b} f(x)\\,dx = F(b) - F(a)$$",
  "",
  "## Mermaid",
  "",
  "```mermaid",
  "flowchart LR",
  "  markdown[Markdown] --> preview[Preview]",
  "  preview --> mermaid[Mermaid]",
  "```",
  "",
  "## Charts",
  "",
  "```chart",
  JSON.stringify({
    type: "line",
    title: "Revenue",
    subtitle: "Quarterly, USD",
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    series: [
      { name: "2024", data: [120, 135, 128, 142, 156, 168] },
      { name: "2025", data: [140, 158, 152, 175, 188, 202] },
    ],
    format: "currency",
  }),
  "```",
  "",
  "```chart",
  JSON.stringify({
    type: "bar",
    title: "Errors by service",
    labels: ["api", "web", "worker", "cron"],
    series: [{ name: "today", data: [4, 12, 2, 8] }],
  }),
  "```",
  "",
  "```chart",
  JSON.stringify({
    type: "donut",
    title: "Token spend",
    labels: ["Sonnet", "Opus", "Haiku"],
    data: [62, 24, 14],
    format: "percent",
  }),
  "```",
  "",
  "## Stock",
  "",
  "```stock",
  JSON.stringify({
    ticker: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    price: 184.92,
    change: 2.34,
    changePercent: 1.28,
    currency: "USD",
    history: [180, 182, 181, 183, 184, 185, 184.92],
    asOf: "May 5, 2026",
  }),
  "```",
  "",
  "## KPIs",
  "",
  "```kpi",
  JSON.stringify([
    { label: "Active users", value: 12840, delta: 1284, deltaPercent: 11.1, history: [10, 11, 11, 12, 12, 13] },
    { label: "Errors", value: 4, delta: -50, deltaPercent: -50, history: [10, 8, 9, 7, 5, 4], trend: "down" },
    { label: "Latency", value: 84, unit: "ms", delta: -6, deltaPercent: -6.7, trend: "down" },
  ]),
  "```",
  "",
  "## Tabs",
  "",
  "```tabs",
  JSON.stringify({
    tabs: [
      { label: "Setup", content: "Install with `npm install` and create a config." },
      { label: "Run", content: "Start the dev server: `npm run dev`.\n\nThen open the browser." },
      { label: "Notes", content: "See the [docs](https://example.com/docs) for **advanced** options." },
    ],
  }),
  "```",
  "",
  "## Multiple choice",
  "",
  "```choice",
  JSON.stringify({
    question: "Pick a deployment target",
    options: [
      { label: "Cloudflare Workers", value: "cf", hint: "Edge runtime, fastest cold start" },
      { label: "AWS Lambda", value: "lambda", hint: "Mature ecosystem" },
      { label: "Self-hosted (Docker)", value: "docker", hint: "Full control" },
    ],
    default: "cf",
  }),
  "```",
  "",
  "## Multi-select",
  "",
  "```select",
  JSON.stringify({
    question: "Which integrations do you need?",
    options: [
      { label: "GitHub", value: "github" },
      { label: "Slack", value: "slack" },
      { label: "Linear", value: "linear" },
      { label: "PagerDuty", value: "pagerduty" },
    ],
    default: ["github", "slack"],
  }),
  "```",
  "",
  "## Callouts",
  "",
  "```info",
  "**Heads up** — callouts support inline `code`, [links](https://example.com), and **bold** text.",
  "```",
  "",
  "```warning",
  "Be careful with this *destructive* operation.",
  "```",
  "",
  "```success",
  "Deployed to production.",
  "```",
  "",
  "```danger",
  "Configuration is invalid — review before continuing.",
  "```",
  "",
  "## Preview card",
  "",
  "```preview",
  JSON.stringify({
    url: "https://example.com/docs/markdown",
    title: "Markdown code fence reference",
    description: "Custom fence languages now render as plain markdown code blocks.",
    site: "Codeplane Docs",
  }),
  "```",
  "",
  "## Badges",
  "",
  "```badge",
  JSON.stringify([
    { label: "v1.4.2", variant: "info" },
    { label: "stable", variant: "success" },
    { label: "beta", variant: "warning" },
    { label: "deprecated", variant: "danger" },
    { label: "internal", variant: "neutral" },
  ]),
  "```",
  "",
  "## Progress",
  "",
  "```progress",
  JSON.stringify([
    { label: "Database migration", value: 86, hint: "Estimated 2 minutes remaining" },
    { label: "Cache warmup", value: 100, variant: "success", hint: "Done" },
    { label: "Disk usage", value: 88, max: 100, variant: "warning", hint: "Approaching capacity" },
    { label: "Failed retries", value: 3, max: 10, variant: "danger" },
  ]),
  "```",
  "",
  "## Timeline",
  "",
  "```timeline",
  JSON.stringify([
    {
      time: "May 5, 09:14",
      title: "Deployment to production",
      description: "Release **v1.4.2** rolled out to `us-east-1`, `eu-west-1`.",
      status: "done",
    },
    {
      time: "May 5, 09:11",
      title: "Smoke tests",
      description: "All 248 tests passed in 92s.",
      status: "done",
    },
    {
      time: "May 5, 09:09",
      title: "Build artefact",
      description: "Image `app:c0ffee` pushed to registry.",
      status: "current",
    },
    {
      time: "May 5, 09:00",
      title: "Canary",
      description: "Awaiting metrics window.",
      status: "pending",
    },
    {
      time: "May 5, 08:42",
      title: "Migration check",
      description: "Schema diff aborted — see logs.",
      status: "failed",
    },
  ]),
  "```",
  "",
  "## Quote",
  "",
  "```quote",
  JSON.stringify({
    text: "Software is a *gas* — it expands to fill its container. Plan accordingly.",
    author: "Nathan Myhrvold",
    role: "Former CTO, Microsoft",
  }),
  "```",
  "",
  "## Rich table",
  "",
  "```table",
  JSON.stringify({
    caption: "Q2 revenue by region",
    columns: [
      { key: "region", label: "Region", align: "left" },
      { key: "users", label: "Users", align: "right", format: "number" },
      { key: "revenue", label: "Revenue", align: "right", format: "currency", currency: "USD" },
      { key: "growth", label: "Growth", align: "right", format: "percent" },
    ],
    rows: [
      { region: "Americas", users: 12840, revenue: 184320, growth: 0.12 },
      { region: "EMEA", users: 8214, revenue: 102450, growth: 0.18 },
      { region: "APAC", users: 6920, revenue: 84120, growth: 0.31 },
      { region: "LATAM", users: 1244, revenue: 14820, growth: -0.04 },
    ],
    total: true,
    zebra: true,
  }),
  "```",
  "",
  "## File tree",
  "",
  "```file-tree",
  JSON.stringify([
    {
      name: "packages/ui",
      type: "folder",
      children: [
        {
          name: "src/components",
          type: "folder",
          children: [
            { name: "markdown.tsx", status: "modified" },
            { name: "markdown-blocks.ts", status: "modified", hint: "plain markdown only" },
            { name: "markdown.css", status: "modified" },
          ],
        },
        {
          name: "src/storybook",
          type: "folder",
          children: [{ name: "fixtures.ts", status: "modified" }],
        },
        { name: "package.json" },
      ],
    },
  ]),
  "```",
  "",
  "## Comparison",
  "",
  "```comparison",
  JSON.stringify({
    title: "Renderer pipeline",
    before: {
      label: "Before",
      content: "Plain code blocks, mermaid, math.\n\nNo charts, tables, choices, or KPIs.",
    },
    after: {
      label: "After",
      content: "Plain code blocks and markdown only.",
    },
  }),
  "```",
  "",
  "## Diff",
  "",
  "```diff",
  "--- a/src/server.ts",
  "+++ b/src/server.ts",
  "@@ -12,7 +12,9 @@",
  " function start(port: number) {",
  "   const app = createApp()",
  "-  app.listen(port)",
  "+  app.listen(port, () => {",
  "+    console.log(`listening on :${port}`)",
  "+  })",
  " }",
  "```",
  "",
  "More at https://example.com/docs",
].join("\n")

export const changes = {
  additions: 18,
  deletions: 6,
}
